name: Build (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Preparing
      run: |
        sudo apt update
        sudo apt install -y build-essential libglfw3-dev libglu1-mesa-dev libglew-dev libx11-dev

    - name: Build Debug
      run: |
        make clean
        make

    - name: Build Release
      run: |
        make clean
        make BUILD=release
