name: Build (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2 and dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-glfw

    - name: Build Debug
      shell: msys2 {0}
      run: |
        mingw32-make clean
        mingw32-make

    - name: Build Release
      shell: msys2 {0}
      run: |
        mingw32-make clean
        mingw32-make BUILD=release
